services:
    _defaults:
        public: false

    'Dividotlab\Slack\Bot\BotFactory': ~
    'Dividotlab\Slack\Bot\BotMan':
        factory: 'Dividotlab\Slack\Bot\BotFactory:create'

    'Dividotlab\Slack\Event\SlackEventHandler':
        arguments:
            - '@serializer'
            - '@event_dispatcher'
        calls:
            - method: setLogger
              arguments: ['@?logger']
